name = "backup check"
targets = ["linux & backupw"]
#disabled = true

script = "backup.sh"
arguments = "$start_file $ok_file"

#              +------+                      +-----
# exp:     27h |  ""  | 27h              27h |
#        +------+    +------+          +------+
#        |     ||    ||     |          |     ||
#       +#.--#+#.--#+#.---+-.---+----#+#---#+#.--#+
# enab: ****************-----------------**********
#         Thu   Fri   Sat   Sun   Mon   Tue   Wen
# dow:     4     5     6     0     1     2     3

run_if = """
    (date('dow') == 3 || date('dow') == 4 || date('dow') == 5) ||
    (date('dow') == 6 && date('time') <= 8) ||
    (date('dow') == 2 && date('time') >= 8)
"""

delay = "30m"
timeout = "8s"

### Default values

[[default]]
name = "start_file"
value = "/tmp/backup.start"

[[default]]
name = "ok_file"
value = "/tmp/backup.ok"

[[default]]
name = "backup_margin_hours"
value = 3

[[default]]
name = "backup_duration_warn"
value = 5

### Checks

[[check]]
desc = "backup too old"
if = "LAST_OK_HOURS > (24+backup_margin_hours)"
classes = ["critical"]

[[check]]
desc = "backup too long"
if = "LAST_DURATION_HOURS > backup_duration_warn"
classes = ["warning"]
