name = "example.com certificate validity"
targets = ["example_com"]
#disabled = true

script = "cert_check.sh"
arguments = "/etc/pki/tls/certs/example.com.crt 15"

delay = "60m"
timeout = "5s"

### Checks

[[check]]
desc = "certificate will expire soon"
if = "WILL_EXPIRE != 0"
classes = ["warning"]
