name = "example.com Website"
targets = ["linux & example"]

script = "curl_expect.sh"
arguments = "http://example.com/ 'used for illustrative examples'"

delay = "5m"
timeout = "20s"

### Checks

[[check]]
desc = "can't find expected content"
if = "FOUND_EXPECTED != 1"
classes = ["critical"]
