name = "memory (RAM and swap)"

script = "mem.sh"
disabled = false

targets = ["linux", "windows"]

delay = "5m"
# WMI can be veeeery slow :(
timeout = "30s"

### Default values
# types: int, float, string
# not "all uppercase" (reserved for probe values)
[[default]]
name = "min_available_ratio"
value = 0.20

[[default]]
name = "warn_swap_ratio"
value = 0.30

### Checks

[[check]]
desc = "critical available memory ratio"
if = "MEM_AVAILABLE_RATIO < min_available_ratio"
classes = ["critical"]

[[check]]
desc = "high swap usage ratio"
if = "SWAP_USED_RATIO > warn_swap_ratio"
classes = ["warning"]
