name = "Apache status (systemd)"
targets = ["linux & systemd & apache"]
#disabled = true

script = "systemctl_status.sh"
arguments = "httpd.service"

delay = "1m"
timeout = "5s"

### Checks

[[check]]
desc = "Apache status"
if = "STATUS != 'active'"
classes = ["critical"]
