# global configuration for Nosee

# Nosee server name (useful if you have multiple Nosee servers)
#name="Test"

# This option helps to ease the global load induced by all SSH connections.
# default: 15s
#start_time_spread = "15s"

# Maximum connection time for a SSH connection. (will trigger a "general" class alert)
# default: 6s
#ssh_connection_time_warn = "6s"

# Currently, nosee will look at $HOME/.ssh/known_hosts for host fingerprints,
# unless you set this to true, accepting blindly any fingerprint.
# This is a potential security issue. (MitM attack)
#ssh_blindtrust_fingerprints = false
